# Use root/example as user/password credentials
version: '3.7'

services:

  mysql:
    image: mysql
    container_name: mysql-db-cnt
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 9002:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - type: bind
        source: ./data
        target: /var/lib/mysql

  adminer:
    image: adminer
    container_name: mysql-adminer-cnt
    restart: always
    ports:
      - 9001:8080

# mysql data is stored in /var/lib/mysql within the container_name
# bind this folder to volume like
# volumes:
#   - mysql-data:/var/lib/mysql

# declare volume like this
#volumes:
#   mysql-data:
#      external: true
