# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql-db-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 9002:3306
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    container_name: mysql-adminer-container
    restart: always
    ports:
      - 9001:8080

# mysql data is stored in /var/lib/mysql within the container_name
# bind this folder to volume like
#volumes:
#   - mysql-data:/var/lib/mysql

# declare volume like this
#volumes:
#   mysql-data:
#      external: true
