# Use root/example as user/password credentials
version: '3.7'

volumes:
  mongo-data:
    external: true
  mongo-config:
    external: true

services:
  mongo:
    image: mongo
    restart: always
    container_name: mongodb-container
    ports:
      - "27017:27017"
#      - "27017-27019:27017-27019"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb-container
